export const IpcMainToRender = {
  updateAvailable: "updateAvailable",
  updateNotAvailable: "updateNotAvailable",
  updateError: "updateError",
  updateDownloadPaused: "updateDownloadPaused",
  updateDownloadFailed: "updateDownloadFailed",
  updateDownloadSuccess: "updateDownloadSuccess",
  updateDownloadProgress: "updateDownloadProgress",
  downloadSuccess: "downloadSuccess",
  downloadFailed: "downloadFailed",
  downloadCancel: "downloadCancel",
  downloadPaused: "downloadPaused",
  downloadProgress: "downloadProgress",
  eventTransfer: "eventTransfer",
  appResume: "appResume",
  openConversation: "openConversation",
};

export const IpcRenderToMain = {
  checkForUpdate: "checkForUpdate",
  downloadUpdate: "downloadUpdate",
  quitAndUpdate: "quitAndUpdate",
  showMainWindow: "showMainWindow",
  openChildWindow: "openChildWindow",
  clearSession: "clearSession",
  minimizeWindow: "minimizeWindow",
  maxmizeWindow: "maxmizeWindow",
  closeWindow: "closeWindow",
  clearChildWindows: "clearChildWindows",
  showMessageBox: "showMessageBox",
  setKeyStore: "setKeyStore",
  getKeyStore: "getKeyStore",
  getKeyStoreSync: "getKeyStoreSync",
  getScreenSource: "getScreenSource",
  startDownload: "startDownload",
  pauseDownload: "pauseDownload",
  resumeDownload: "resumeDownload",
  cancelDownload: "cancelDownload",
  showInputContextMenu: "showInputContextMenu",
  updateUnreadCount: "updateUnreadCount",
  newMessageTrigger: "newMessageTrigger",
  setUserCachePath: "setUserCachePath",
  getDataPath: "getDataPath",
  dragFile: "dragFile",
  appUpdate: "appUpdate",
  showLogsInFinder: "showLogsInFinder",
  prepareUploadLogs: "prepareUploadLogs",
  hotRelaunch: "hotRelaunch",
  eventTransfer: "eventTransfer",
  checkChildWindowStatus: "checkChildWindowStatus",
  checkMediaAccess: "checkMediaAccess",
  oauthLogin: "oauthLogin",
};
